spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/banking'
    username: 'postgres'
    password: 123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      driver-class-name: org.postgresql.Driver
  main:
    banner-mode: off
    lazy-initialization: true
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        default_schema: 'banking_user'